version: '3.0'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: tcu_english
            MYSQL_DATABASE: tcu_english
            MYSQL_USER: tcu_english
            MYSQL_PASSWORD: tcu_english
	tcuenglishapp:
        depends_on:
            - db
		build: .
        restart: always
volumes:
    db_data: